import os

print("\nLUNAR MISSION REPORT\n")

image_name = input("Image Name: ")

craters = input("Detected Craters: ")

hazard = input("Hazard Coverage (%): ")

score = input("Landing Score (0-100): ")

if float(score) >= 70:
    status = "SAFE FOR LANDING"
elif float(score) >= 40:
    status = "MODERATE RISK"
else:
    status = "HIGH RISK"

report = f"""
====================================
LUNAR MISSION ANALYSIS REPORT
====================================

Image:
{image_name}

Detected Craters:
{craters}

Hazard Coverage:
{hazard} %

Landing Score:
{score} / 100

Assessment:
{status}

Generated By:
Lunar Terrain Analyzer

====================================
"""

os.makedirs("outputs", exist_ok=True)

with open(
    "outputs/mission_report.txt",
    "w",
    encoding="utf-8"
) as f:
    f.write(report)

print("\nReport Saved:")
print("outputs/mission_report.txt")